In [154]:
import pandas as pd

In [107]:
df = pd.read_csv("../data/ONINE_FOOD_DELIVERY_ANALYSIS.csv")
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,8/12/2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/8/2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/8/2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2/4/2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  object
 1   Customer_ID          100000 non-null  object
 2   Customer_Age         49907 non-null   float64
 3   Customer_Gender      75144 non-null   object
 4   City                 83274 non-null   object
 5   Area                 83315 non-null   object
 6   Restaurant_ID        100000 non-null  object
 7   Restaurant_Name      100000 non-null  object
 8   Cuisine_Type         83115 non-null   object
 9   Order_Date           98986 non-null   object
 10  Order_Time           98002 non-null   object
 11  Delivery_Time_Min    66641 non-null   float64
 12  Distance_km          66530 non-null   float64
 13  Order_Value          66673 non-null   float64
 14  Discount_Applied     83285 non-null   float64
 15  Final_Amount         44303 non-null   float64
 16  Payment_Mode         80089 non-null   object
 17  Order_Status         100000 non-null  object
 18  Cancellation_Reason  9031 non-null    object
 19  Delivery_Partner_ID  100000 non-null  object
 20  Delivery_Rating      83477 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  object
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(16)
memory usage: 19.1+ MB

In [109]:
df.isnull().sum()

Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating        16523
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

In [110]:
df.describe()

,Customer_Age,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Delivery_Rating,Restaurant_Rating,Profit_Margin
count,49907.000000,66641.000000,66530.000000,66673.000000,83285.000000,44303.000000,83477.000000,100000.000000,100000.000000
mean,38.976516,127.475923,16.449242,2081.830126,93.936243,1961.101190,2.991531,4.249680,0.150362
std,12.372157,90.805839,12.256742,1553.628891,108.209904,1557.354417,1.414108,0.722554,0.201888
min,18.000000,20.000000,1.000000,150.000000,0.000000,-150.000000,1.000000,3.000000,-0.200000
25%,28.000000,45.000000,5.470000,673.000000,20.000000,559.000000,2.000000,3.600000,-0.020000
50%,39.000000,120.000000,9.970000,1197.000000,50.000000,1156.000000,3.000000,4.200000,0.150000
75%,50.000000,210.000000,27.430000,3494.000000,100.000000,3375.000000,4.000000,4.900000,0.320000
max,60.000000,300.000000,40.000000,5000.000000,300.000000,4980.000000,5.000000,5.500000,0.500000

In [111]:
df.duplicated().sum()

np.int64(0)

In [112]:
# Checking duplicates in Order ID
df["Order_ID"].duplicated().sum()

np.int64(0)

In [113]:
# Dropping Order time since it has no values 
df = df.drop(columns=["Order_Time"])

In [114]:
# Handling the below category values with unKnown
categorical_columns = [
    "Customer_Gender",
    "City",
    "Area",
    "Cuisine_Type",
    "Payment_Mode"
]

for col in categorical_columns:
    df[col] = df[col].fillna("Unknown")

In [115]:
# Using median to fill all the missing values for the customer Age 
df["Customer_Age"] = df["Customer_Age"].fillna(df["Customer_Age"].median())

In [116]:
#Making sure that there are any outliers in the Delivery Time
Q1 = df["Delivery_Time_Min"].quantile(0.25)
Q3 = df["Delivery_Time_Min"].quantile(0.75)
IQR = Q3 - Q1
LB = Q1- 1.5 * IQR
UB = Q3 + 1.5 * IQR
Outliers = df[(df["Delivery_Time_Min"] < LB) | (df["Delivery_Time_Min"] > UB)]
print("Number of outliers:", len(Outliers))

Number of outliers: 0

In [117]:
df["Delivery_Time_Min"] = pd.to_numeric(
    df["Delivery_Time_Min"], errors="coerce"
)

df["Delivery_Time_Min"] = df["Delivery_Time_Min"].fillna(
    df["Delivery_Time_Min"].median()
)

In [118]:
#Making sure that there are any outliers in the Distance KM
Q1 = df["Distance_km"].quantile(0.25)
Q3 = df["Distance_km"].quantile(0.75)
IQR = Q3 - Q1
LB = Q1- 1.5 * IQR
UB = Q3 + 1.5 * IQR
Outliers = df[(df["Distance_km"] < LB) | (df["Distance_km"] > UB)]
print("Number of outliers:", len(Outliers))

Number of outliers: 0

In [119]:
df["Distance_km"] = df["Distance_km"].fillna(df["Distance_km"].median())

In [120]:
#Checking Outliers for order value
Q1 = df["Order_Value"].quantile(0.25)
Q3 = df["Order_Value"].quantile(0.75)
IQR = Q3 - Q1
LB = Q1- 1.5 * IQR
UB = Q3 + 1.5 * IQR
Outliers = df[(df["Order_Value"] < LB) | (df["Order_Value"] > UB)]
print("Number of outliers:", len(Outliers))

Number of outliers: 0

In [121]:
df["Order_Value"] = df["Order_Value"].fillna(df["Order_Value"].median())

In [122]:
#Cancellation_Reason
df["Cancellation_Reason"].value_counts(dropna=False)

Cancellation_Reason
NaN                   90969
Late Delivery          3059
Customer Cancelled     2993
Restaurant Issue       2979
Name: count, dtype: int64

In [123]:
#not every cancelled order has a cancellation reason. Some of those may be delivered orders. so comparing order status with cancellation reason
pd.crosstab(df["Order_Status"], df["Cancellation_Reason"], dropna=False)

Cancellation_Reason,Customer Cancelled,Late Delivery,Restaurant Issue,NaN
Order_Status,,,,
Cancelled,2993,3059,2979,6005
Delivered,0,0,0,84964

In [124]:
#For cancelled orders where the reason is missing, we'll use Unknown.
#For delivered orders where the reason is missing, we'll use Not Cancelled.
df.loc[
    (df["Order_Status"] == "Cancelled") & (df["Cancellation_Reason"].isna()),
    "Cancellation_Reason"
] = "Unknown"

df.loc[
    (df["Order_Status"] == "Delivered") & (df["Cancellation_Reason"].isna()),
    "Cancellation_Reason"
] = "Not Cancelled"

In [125]:
df["Cancellation_Reason"].value_counts(dropna=False)

Cancellation_Reason
Not Cancelled         84964
Unknown                6005
Late Delivery          3059
Customer Cancelled     2993
Restaurant Issue       2979
Name: count, dtype: int64

In [126]:
# Restaurant_Rating
df["Restaurant_Rating"].describe()

count    100000.000000
mean          4.249680
std           0.722554
min           3.000000
25%           3.600000
50%           4.200000
75%           4.900000
max           5.500000
Name: Restaurant_Rating, dtype: float64

In [127]:
(df["Restaurant_Rating"] > 5).sum()

np.int64(18019)

In [128]:
# Usually ratings are expected to be in a range of 1 - 5, here we have values which are more than 5. So capping those values with 5 
df["Restaurant_Rating"] = df["Restaurant_Rating"].clip(upper=5)

In [129]:
df["Restaurant_Rating"].max()

np.float64(5.0)

In [130]:
# Peak Hour
df["Peak_Hour"].value_counts(dropna=False)

Peak_Hour
False    33585
True     33453
NaN      32962
Name: count, dtype: int64

In [131]:
df["Peak_Hour"].dtypes

dtype('O')

In [132]:
# Since Peak_Hour is a Boolean field, we shouldn't fill the missing values with "Unknown" because that would change its data type.
df["Peak_Hour"] = df["Peak_Hour"].map({
    True: "Peak Hour",
    False: "Non-Peak Hour"
}).fillna("Unknown")

In [133]:
# Delivery Rating 
df["Delivery_Rating"].value_counts(dropna=False)

Delivery_Rating
2.0    16896
4.0    16885
1.0    16818
NaN    16523
5.0    16470
3.0    16408
Name: count, dtype: int64

In [134]:
# Rating is not applicable when an order is cancelled
df.groupby("Order_Status")["Delivery_Rating"].agg(
    ["count", "mean", "min", "max"]
)

              count      mean  min  max
Order_Status
Cancelled     12561  2.989252  1.0  5.0
Delivered     70916  2.991934  1.0  5.0

In [135]:
#For all cancelled orders, set the Delivery_Rating value to None
df.loc[df["Order_Status"] == "Cancelled", "Delivery_Rating"] = None

# Finding Median median of delivered ratings only.
delivered_median = df.loc[
    df["Order_Status"] == "Delivered", "Delivery_Rating"
].median()

delivered_median

np.float64(3.0)

In [136]:
# Filling missing Delivery_Rating values only for delivered orders
df.loc[
    (df["Order_Status"] == "Delivered") &
    (df["Delivery_Rating"].isna()),
    "Delivery_Rating"
] = delivered_median

In [137]:
## Cancelled → NaN because delivery rating doesn't apply.
## Delivered → actual ratings retained
## Missing delivered ratings → filled with the median of delivered ratings only.
df.groupby("Order_Status")["Delivery_Rating"].agg(
    ["count", "mean", "min", "max"]
)

              count      mean  min  max
Order_Status
Cancelled         0       NaN  NaN  NaN
Delivered     84964  2.993268  1.0  5.0

In [138]:
df["Discount_Applied"].describe()

count    83285.000000
mean        93.936243
std        108.209904
min          0.000000
25%         20.000000
50%         50.000000
75%        100.000000
max        300.000000
Name: Discount_Applied, dtype: float64

In [139]:
df["Discount_Applied"].isna().sum()

np.int64(16715)

In [140]:
#Making sure that there are any outliers in the Discounts
Q1 = df["Discount_Applied"].quantile(0.25)
Q3 = df["Discount_Applied"].quantile(0.75)
IQR = Q3 - Q1
LB = Q1- 1.5 * IQR
UB = Q3 + 1.5 * IQR
Outliers = df[(df["Discount_Applied"] < LB) | (df["Discount_Applied"] > UB)]
print("Number of outliers:", len(Outliers))

Number of outliers: 16600

In [141]:
# Missing discount values were filled with the median discount of 50 because some discount values were unusually high.
df["Discount_Applied"] = df["Discount_Applied"].fillna(df["Discount_Applied"].median())

In [142]:
# Final amount
df["Final_Amount"].describe()

count    44303.000000
mean      1961.101190
std       1557.354417
min       -150.000000
25%        559.000000
50%       1156.000000
75%       3375.000000
max       4980.000000
Name: Final_Amount, dtype: float64

In [143]:
# Final order Amount shouldn't be negative, usually it should be 0 or more than that. 
df[df["Final_Amount"] < 0][["Order_Value", "Discount_Applied", "Final_Amount", "Order_Status"]
].head(20)

      Order_Value  Discount_Applied  Final_Amount Order_Status
104         187.0             300.0        -113.0    Delivered
132         175.0             300.0        -125.0    Delivered
284         246.0             300.0         -54.0    Delivered
306         194.0             300.0        -106.0    Delivered
359         285.0             300.0         -15.0    Delivered
576         247.0             300.0         -53.0    Delivered
619         234.0             300.0         -66.0    Delivered
729         210.0             300.0         -90.0    Delivered
891         195.0             300.0        -105.0    Cancelled
1148        204.0             300.0         -96.0    Delivered
1517        254.0             300.0         -46.0    Delivered
1589        245.0             300.0         -55.0    Cancelled
1683        286.0             300.0         -14.0    Delivered
1777        210.0             300.0         -90.0    Delivered
1813        167.0             300.0        -133.0    Delivered
2099        295.0             300.0          -5.0    Cancelled
2149        221.0             300.0         -79.0    Delivered
2705        176.0             300.0        -124.0    Delivered
2871        298.0             300.0          -2.0    Cancelled
2904        252.0             300.0         -48.0    Cancelled

In [144]:
(df["Final_Amount"] < 0).sum()

np.int64(773)

In [145]:
(df["Discount_Applied"] > df["Order_Value"]).sum()

np.int64(773)

In [146]:
(df["Final_Amount"] == df["Order_Value"] - df["Discount_Applied"]).value_counts()

False    55697
True     44303
Name: count, dtype: int64

In [147]:
df["Final_Amount"].isna().sum()

np.int64(55697)

In [148]:
#Filling all the missing value using total amount and discount value 
df["Final_Amount"] = df["Final_Amount"].fillna(df["Order_Value"] - df["Discount_Applied"])

In [155]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [156]:
df.isna().sum()

Order_ID                   0
Customer_ID                0
Customer_Age               0
Customer_Gender            0
City                       0
Area                       0
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type               0
Order_Date              1014
Delivery_Time_Min          0
Distance_km                0
Order_Value                0
Discount_Applied           0
Final_Amount               0
Payment_Mode               0
Order_Status               0
Cancellation_Reason        0
Delivery_Partner_ID        0
Delivery_Rating        15036
Restaurant_Rating          0
Order_Day                  0
Peak_Hour                  0
Profit_Margin              0
dtype: int64

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  object
 1   Customer_ID          100000 non-null  object
 2   Customer_Age         100000 non-null  float64
 3   Customer_Gender      100000 non-null  object
 4   City                 100000 non-null  object
 5   Area                 100000 non-null  object
 6   Restaurant_ID        100000 non-null  object
 7   Restaurant_Name      100000 non-null  object
 8   Cuisine_Type         100000 non-null  object
 9   Order_Date           98986 non-null   datetime64[ns]
 10  Delivery_Time_Min    100000 non-null  float64
 11  Distance_km          100000 non-null  float64
 12  Order_Value          100000 non-null  float64
 13  Discount_Applied     100000 non-null  float64
 14  Final_Amount         100000 non-null  float64
 15  Payment_Mode         100000 non-null  object
 16  Order_Status         100000 non-null  object
 17  Cancellation_Reason  100000 non-null  object
 18  Delivery_Partner_ID  100000 non-null  object
 19  Delivery_Rating      84964 non-null   float64
 20  Restaurant_Rating    100000 non-null  float64
 21  Order_Day            100000 non-null  object
 22  Peak_Hour            100000 non-null  object
 23  Profit_Margin        100000 non-null  float64
dtypes: datetime64[ns](1), float64(9), object(14)
memory usage: 18.3+ MB